apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ssl-i-orangesys-io
  namespace: apigateway
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "i-orangesys-io-ingress"
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
  - hosts:
    - i.orangesys.io
    secretName: 201712-i-orangesys-io
  rules:
  - host:
    http:
      paths:
      - path:
        backend:
          serviceName: orangesys-kong-proxy
          servicePort: 80
